name: "test all folders"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  node_tests:
    env: 
      ALGORITHM: ${{ secrets.ALGORITHM }}
      API_KEY: ${{ secrets.API_KEY }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
      DATABASE: ${{ secrets.DATABASE }}
      GEMINI_API_2: ${{ secrets.GEMINI_API_2 }}
      KEY: ${{ secrets.KEY }}
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      PASSWORD: ${{ secrets.PASSWORD }}
      PORT: ${{ secrets.PORT }}
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: '22.x'
      - run: npm install
      - run: npm test