name: "test all folders"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  node_tests:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@3
      - uses: actions/setup-node
        with: 
          node-version: '22.x'
      - run: npm install
      - run: npm test